In [ ]:
Ax = b
AinvAx = x = Ainvb
#A is matrix # x column vector # b vector

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([1,2])


# better to use solve() than inv()

In [9]:
x = np.linalg.inv(A).dot(b)
x

array([2.22044605e-16, 5.00000000e-01])

In [8]:
x = np.linalg.solve(A,b)
x

array([0. , 0.5])

In [13]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(A,b)
x

array([1500.,  700.])

# loading data

In [15]:
import numpy as np
x = []
for line in open('../../linear_regression_class/data_2d.csv'):
    row = line.split(",")
    sample = map(float, row) #casting string into float
    x.append(sample)

x = np.array(x)
x

FileNotFoundError: [Errno 2] No such file or directory: '../../linear_regression_class/data_2d.csv'